name: Heroku

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Deploying to Heroku
    - uses: actions/checkout@v2
    - uses: akhileshns/heroku-deploy@master
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "neerajlag@gmail.com"
        heroku_email: "calm-garden-78445"
